-- Mercadinho IF • Importação de usuários com saldo zerado
-- Mantém o usuário Administrador existente. Este SQL apenas cria/atualiza os emails listados.
-- Senha inicial de cada pessoa: parte antes do @ + @123. Ex: marina@123
-- Atenção: se algum código gerado bater com um código já existente no banco, use o PHP de importação em vez deste SQL.
BEGIN TRANSACTION;

INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Daiane', 'daiane@italianofacil.com.br', '$2y$12$PaqtI1AWRLMgaJhfq4e9Au1oWEx1w6zlto6vdKQRK/aWlUmEpgHUa', 'admin', 'lideranca', 'K48JM', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Amanda', 'amanda@italianofacil.com.br', '$2y$12$eBSd2/S9uAcGeUmX9K2S4emOVIePiBxzQMpn2yWMrW6wK42s2N6pe', 'admin', 'lideranca', 'WUNRP', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Ronaldo', 'ronaldo@italianofacil.com.br', '$2y$12$yiMWUFpWLn.M39z/kVK6Ne3vC0QV.SHolG15DYUxyVsVmcue5iISG', 'admin', 'lideranca', '8KHTK', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Sheron', 'sheron@italianofacil.com', '$2y$12$Iu5iix7Sseb8FpzAZb0UzOb2vRVMqM.GLLaGNeCMRUYjRJZimCm7K', 'admin', 'lideranca', 'ZP73F', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Felipe', 'felipe@italianofacil.com', '$2y$12$lFPxiNcfoypix8Jmiz9bE.j0uAMMfUMEbkpDlXUavx.VKHyDeahtm', 'user', 'suporte', 'H667V', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Nicole', 'nicole@italianofacil.com', '$2y$12$ToihvF0KDFQ9GV44c.ugsOZJ5Fg3D.27JVIzSDvw2ZKuWGGeUbXN2', 'user', 'suporte', '4WAQ8', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Caroline', 'caroline@italianofacil.com', '$2y$12$YB5eLNAysL02aMGNyEQNhu0n.Qo6FY5pQjB6m16x45tNPpnjqgzQq', 'user', 'suporte', 'LFBTH', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Gabriel', 'gabriel@italianofacil.com', '$2y$12$3Wk87ZEFPVe52l6bJgJp4uCCOgudgx97jqjQjol1lBhuLom5Gej8u', 'user', 'suporte', 'VCDLF', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Adryan', 'adryan@italianofacil.com', '$2y$12$Yh551onBida9BFa7i50ROuBUMId3kzEvpP6XU.8SuddDv2iA89MmK', 'user', 'suporte', 'PBFH4', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Maurício', 'mauricio@italianofacil.com', '$2y$12$e8WSRhf1GsDxlR18kvPGR.QsZxuu8RaUQ/j0IHeYKCRxPPFtLrDvq', 'user', 'marketing', '6CFLD', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Emmanoel', 'emmanoel@italianofacil.com', '$2y$12$mROm.73s3HlwGI.Xd/zESOF1RpkKiPZcI25RtlWKcfqlrq/zmCjyy', 'user', 'marketing', '3GX7Z', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Daniele', 'daniele@italianofacil.com', '$2y$12$aWqAe86qoaay1xwd68HBHO3Kim6R9ntFJ6RPX3s3sYFEnSvG2J0r6', 'admin', 'cuidado_bem_estar', 'KSSV2', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Nicole Oliveira', 'nicoleoliveira@italianofacil.com', '$2y$12$38hY6uMsyWvsvZsrUs4fjOaJ1lg/1DCln7MoBQLgMliYavjUCZ4AC', 'user', 'cuidado_bem_estar', 'W6HX6', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Claudia', 'claudia@italianofacil.com', '$2y$12$U.w3M6CTDKdpx2.cEnxViOWA3OX5IhotwmzvxRH/vnAcNVchyg3Ja', 'admin', 'rh', 'BKPS5', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Joshua', 'joshua@italianofacil.com', '$2y$12$vKb7Zp6Gtsx3czLx4g2EDufSdDJXHVzIj2Zh.YQYJq5TV.yMN9aBe', 'user', 'tecnologia', 'NBREG', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Marina', 'marina@italianofacil.com', '$2y$12$aAbhxSCxr9s.Tgik9oEqDOkh53sZUnDfQsTqkR4KI0CxrABEhq4eC', 'user', 'comercial', 'PN55T', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Heloisa', 'heloisa@italianofacil.com', '$2y$12$zUmS5g2Dq3RDqHDd1kDlde9QsAx1WmUPKOOrYnmOLdVIjIp4XVR62', 'user', 'comercial', 'HCE9Y', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Kelvyn', 'kelvyn@italianofacil.com', '$2y$12$2C/9cyH79TJJFyGpjkiit.WFF1pU0MNdxhiYhsY6ejpa8dll241ZG', 'user', 'comercial', 'LQMTH', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Gabriel Martins', 'gabrielmartins@italianofacil.com', '$2y$12$.o4C4X8APs3wSd0oXI6aZeO3Wztz4EW933SXw4RwhjFAZOwadOhN.', 'user', 'comercial', '9FSUN', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Victoria', 'victoria@italianofacil.com', '$2y$12$hZJvM6KMqe/0itS9uVsVL.jzD4JNwBRWXFA.ZlMISdNIeQo1e02hu', 'user', 'comercial', 'WJ8QM', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Alana', 'alana@italianofacil.com', '$2y$12$yd/oIONjxt4WPt2HTFRqSO2SakJ/bSooOAVdD/9liU5OK7t1mQwqe', 'user', 'comercial', '6SNH5', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Bruna', 'bruna@italianofacil.com', '$2y$12$9HFcu9Yy8o9NkBuk/9ZwUORT4r86rgXvZtSnWIYrOal0/V61ST3xy', 'user', 'comercial', '25GUM', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Mellany', 'mellany@italianofacil.com', '$2y$12$uBFjScZ3JlO2jr4PSSXSFuDpAxfFakEaxfAKR3Ez2pfms4Dvz7VOG', 'user', 'financeiro', 'QTXJA', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');
INSERT INTO users (name, email, password_hash, role, sector, code, balance, active, created_at, updated_at) VALUES ('Melanie', 'melanie@italianofacil.com', '$2y$12$YU3yhc9piMTYlvjWEgd9z.8z3jHFbiLcnbQBDkpzTYHCyg6RCJIcO', 'user', 'financeiro', 'HF5VM', 0, 1, datetime('now','localtime'), datetime('now','localtime')) ON CONFLICT(email) DO UPDATE SET name = excluded.name, password_hash = excluded.password_hash, role = excluded.role, sector = excluded.sector, balance = 0, active = 1, updated_at = datetime('now','localtime');

COMMIT;
